name: Some workflow

on:
  issue_comment:
    types: [created]

jobs:
  comment:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        if: ${{ github.issue.assignee.login == 'ShamansJackal' }}
        with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: |
          ${{ github.actor }} Created comment:
          Message: ${{ github.event.comment.html_url }}
          
          Repository: ${{ github.repository }}    
