name: Some workflow

on:
  issue_comment:
    types: [created]

jobs:
  comment:
    if: always()
    runs-on: ubuntu-latest
    steps:
     - name: send telegram message on push
       uses: appleboy/telegram-action@0.0.3
       with:
        to: 210583358
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ toJson(github) }}
          
          Repository: ${{ github.repository }}
