name: Some workflow

on:
  issue_comment:
    types: [created]

jobs:
  comment:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        env:
          userDict: "{\"ShamansJackal\":210583358}"
        with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event }}
          
          Repository: ${{ github.repository }}    
