name: Some workflow

on:
  issue_comment:
    types: [created]

jobs:
  comment:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
         to: ${{ secrets.TELEGRAM_TO }}
         if: ${{ github.issue.assignee.login != 'ShamansJackal' }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: |
          ${{ github.actor }} Created comment:
          Message: ${{ toJson(github.event.issue.assignee) }}
          
          Repository: ${{ github.repository }}    
