name: Some workflow

on:
  issue_comment:
    types: [created]

jobs:
  comment:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.TELEGRAM_TO }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.TELEGRAM_TOKEN}} | sed 's/./& /g'       
